// preload.js -- safe bridge between renderer and main
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('cap', {
  onCaption: (cb) => ipcRenderer.on('caption', (e, obj) => cb(obj)),
  minimize: () => ipcRenderer.send('win-min'),
  close: () => ipcRenderer.send('win-close'),
  setAlwaysOnTop: (v) => ipcRenderer.send('win-top', v),
  raiseTop: () => ipcRenderer.send('win-raise'),
  sendToChatGPT: (text) => ipcRenderer.send('send-chatgpt', text),
  sendAction: (id, selectedText) => ipcRenderer.send('send-action', id, selectedText),
  sendKeyword: (text) => ipcRenderer.send('send-keyword', text),
  recoverGpt: () => ipcRenderer.send('recover-gpt'),
  resetGptSession: () => ipcRenderer.send('reset-gpt-session'),
  setAnswerInApp: (on) => ipcRenderer.send('set-answer-in-app', on),
  setMode: (m) => ipcRenderer.send('set-mode', m),
  setHotkeys: (cfg) => ipcRenderer.invoke('set-hotkeys', cfg),
  setStealth: (on) => ipcRenderer.send('set-stealth', on),
  getPrivacy: () => ipcRenderer.invoke('get-privacy'),
  setPrivacy: (cfg) => ipcRenderer.invoke('set-privacy', cfg),
  privacyAction: (action) => ipcRenderer.invoke('privacy-action', action),
  onPrivacyState: (cb) => ipcRenderer.on('privacy-state', (e, state) => cb(state)),
  micMute: (state, device) => ipcRenderer.invoke('mic-mute', state, device),
  micList: () => ipcRenderer.invoke('mic-list'),
  setDefaultMic: (id) => ipcRenderer.invoke('set-default-mic', id),
  onHotkeyMute: (cb) => ipcRenderer.on('hotkey-mute', () => cb()),
  onHotkeyLatest: (cb) => ipcRenderer.on('hotkey-latest', () => cb()),
  toggleInspector: (on) => ipcRenderer.send('toggle-inspector', on),
  onInspectorClosed: (cb) => ipcRenderer.on('inspector-closed', () => cb()),
  setTeleprompter: (on) => ipcRenderer.send('set-teleprompter', on),
  setConsole: (on) => ipcRenderer.send('set-console', on),
  setScrollParams: (p) => ipcRenderer.send('set-scroll-params', p),
  onDebugLog: (cb) => ipcRenderer.on('debug-log', (e, d) => cb(d)),
  getDebugLog: () => ipcRenderer.invoke('get-debug-log'),
  getKeys: () => ipcRenderer.invoke('get-keys'),
  saveKey: (engine, key) => ipcRenderer.invoke('save-key', engine, key),
  setEngine: (engine) => ipcRenderer.send('set-engine', engine),
  setEngines: (speaker, mic) => ipcRenderer.send('set-engines', { speaker, mic }),
  setMicName: (name) => ipcRenderer.send('set-mic-name', name),
  teleFeed: (text, status) => ipcRenderer.send('tele-feed', text, status),
  onEngineStatus: (cb) => ipcRenderer.on('engine-status', (e, s) => cb(s)),
  installLocal: () => ipcRenderer.invoke('install-local'),
  onInstallProgress: (cb) => ipcRenderer.on('install-progress', (e, l) => cb(l)),
  onBrowserMic: (cb) => ipcRenderer.on('browser-mic', (e, s) => cb(s)),
  onConsoleClosed: (cb) => ipcRenderer.on('console-closed', () => cb()),
  onToggleAutoscroll: (cb) => ipcRenderer.on('toggle-autoscroll', () => cb()),
  onGptStatus: (cb) => ipcRenderer.on('gpt-status', (e, s) => cb(s)),
  onGptResult: (cb) => ipcRenderer.on('gpt-result', (e, r) => cb(r)),
  onGptAnswer: (cb) => ipcRenderer.on('gpt-answer', (e, r) => cb(r)),
  onAdvanceSelection: (cb) => ipcRenderer.on('advance-selection', (e, id) => cb(id)),
  copy: (text) => ipcRenderer.send('clip', text),
  setLcOpacity: (alpha) => ipcRenderer.send('lc-opacity', alpha),
  ensureLiveCaptions: () => ipcRenderer.send('ensure-lc'),
  resize: (w, h) => ipcRenderer.send('resize', w, h),
  setAppOpacity: (v) => ipcRenderer.send('app-opacity', v),
  saveFile: (text) => ipcRenderer.invoke('save-file', text),
  getPrompts: () => ipcRenderer.invoke('get-prompts'),
  getContext: () => ipcRenderer.invoke('get-context'),
  getTermVocab: () => ipcRenderer.invoke('get-term-vocab'),
  setContextEnabled: (on) => ipcRenderer.invoke('set-context-enabled', on),
  previewContext: (q) => ipcRenderer.invoke('preview-context', q),
  openContextDir: () => ipcRenderer.invoke('open-context-dir'),
  getVersion: () => ipcRenderer.invoke('get-version'),
  saveAudio: (id, data) => ipcRenderer.invoke('save-audio', id, data),
  getAudio: (id) => ipcRenderer.invoke('get-audio', id),
  deleteAudio: (id) => ipcRenderer.invoke('delete-audio', id)
});
